services:
  mysqldb:
    image: mysql:8.0.20
    container_name: mysql_container
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mvc_crud
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/testdump.sql:/docker-entrypoint-initdb.d/testdump.sql
    networks:
      - app-tier
    restart: always
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysqldb
    networks:
      - app-tier
    restart: always
networks:
  app-tier:
    driver: bridge
volumes:
  dbdata:
